export const currencies = {
    'AUD': { name: 'Australian Dollar', tag: 'AUD', rate: 1.5512},
    'BGN': { name: 'Bulgarian Lev', tag: 'BGN', rate: 1.9558},
    'BRL': { name: 'Brazilian Real', tag: 'BRL', rate: 3.8192},
    'CAD': { name: 'Canadian Dollar', tag: 'CAD', rate: 1.4966},
    'CHF': { name: 'Swiss Franc', tag: 'CHF', rate: 1.1673},
    'CNY': { name: 'Chinese Yen (Yuan)', tag: 'CNY', rate: 7.8356},
    'CZK': { name: 'Czech Koruna', tag: 'CAK', rate: 25.653},
    'DKK': { name: 'Danish Krone', tag: 'DKK', rate: 7.4415},
    'EUR': { name: 'Euro', tag: 'EUR', rate: 1},
    'GBP': { name: 'Pound Sterling', tag: 'GBP', rate: 0.88183},
    'HKD': { name: 'Hong Kong Dollar', tag: 'HKD', rate: 9.2563},
    'HRK': { name: 'Croatian Kuna', tag: 'HRK', rate: 7.5543},
    'HUF': { name: 'Forint', tag: 'HUF', rate: 313.96},
    'IDR': { name: 'Rupiah', tag: 'IDR', rate: 16009.0},
    'ILS': { name: 'New Israeli Sheqel', tag: 'ILS', rate: 4.1392},
    'INR': { name: 'Indian Rupee', tag: 'INR', rate: 76.302},
    'JPY': { name: 'Japanese Yen', tag: 'JPY', rate: 133.37},
    'KRW': { name: 'Korean Won', tag: 'KRW', rate: 1286.9},
    'MXN': { name: 'Mexican Peso', tag: 'MXN', rate: 22.08},
    'MYR': { name: 'Malaysian Ringgit', tag: 'MYR', rate: 4.8057},
    'NOK': { name: 'Norwegian Krone', tag: 'NOK', rate: 9.8228},
    'NZD': { name: 'New Zealand Dollar', tag: 'NZD', rate: 1.7193},
    'PHP': { name: 'Philippine Peso', tag: 'PHP', rate: 59.978},
    'PLN': { name: 'Zloty', tag: 'PLN', rate: 4.202},
    'RON': { name: 'Romanian Lev', tag: 'RON', rate: 4.6337},
    'RUB': { name: 'Russian Ruble', tag: 'RUB', rate: 69.548},
    'SEK': { name: 'Swedish Krona', tag: 'SEK', rate: 9.968},
    'SGD': { name: 'Singapore Dollar', tag: 'SGD', rate: 1.5953},
    'THB': { name: 'Thai Baht', tag: 'THB', rate: 38.626},
    'TRY': { name: 'Turkish lira', tag: 'TRY', rate: 4.5823},
    'USD': { name: 'US Dollar', tag: 'USD', rate: 1.1847},
    'ZAR': { name: 'South African Rand', tag: 'ZAR', rate: 16.008}
}

