export const _currencies: Currencies = {
    'AUD': { name: 'Australian Dollar', tag: 'AUD', rate: 1.5512, symbol: '$' },
    'BGN': { name: 'Bulgarian Lev', tag: 'BGN', rate: 1.9558, symbol: 'лв' },
    'BRL': { name: 'Brazilian Real', tag: 'BRL', rate: 3.8192, symbol: 'R$' },
    'CAD': { name: 'Canadian Dollar', tag: 'CAD', rate: 1.4966, symbol: 'C$' },
    'CHF': { name: 'Swiss Franc', tag: 'CHF', rate: 1.1673, symbol: 'SFr.' },
    'CNY': { name: 'Chinese Yen (Yuan)', tag: 'CNY', rate: 7.8356, symbol: '¥' },
    'CZK': { name: 'Czech Koruna', tag: 'CZK', rate: 25.653, symbol: 'Kč' },
    'DKK': { name: 'Danish Krone', tag: 'DKK', rate: 7.4415, symbol: 'kr.' },
    'EUR': { name: 'Euro', tag: 'EUR', rate: 1, symbol: '€' },
    'GBP': { name: 'Pound Sterling', tag: 'GBP', rate: 0.88183, symbol: '£' },
    'HKD': { name: 'Hong Kong Dollar', tag: 'HKD', rate: 9.2563, symbol: 'HK$' },
    'HRK': { name: 'Croatian Kuna', tag: 'HRK', rate: 7.5543, symbol: 'kn' },
    'HUF': { name: 'Forint', tag: 'HUF', rate: 313.96, symbol: 'Ft' },
    'IDR': { name: 'Rupiah', tag: 'IDR', rate: 16009.0, symbol: 'Rp' },
    'ILS': { name: 'New Israeli Sheqel', tag: 'ILS', rate: 4.1392, symbol: '₪' },
    'INR': { name: 'Indian Rupee', tag: 'INR', rate: 76.302, symbol: '₹' },
    'JPY': { name: 'Japanese Yen', tag: 'JPY', rate: 133.37, symbol: '¥' },
    'KRW': { name: 'Korean Won', tag: 'KRW', rate: 1286.9, symbol: '₩' },
    'MXN': { name: 'Mexican Peso', tag: 'MXN', rate: 22.08, symbol: '$' },
    'MYR': { name: 'Malaysian Ringgit', tag: 'MYR', rate: 4.8057, symbol: 'RM' },
    'NOK': { name: 'Norwegian Krone', tag: 'NOK', rate: 9.8228, symbol: 'kr' },
    'NZD': { name: 'New Zealand Dollar', tag: 'NZD', rate: 1.7193, symbol: 'NZ$' },
    'PHP': { name: 'Philippine Peso', tag: 'PHP', rate: 59.978, symbol: '₱' },
    'PLN': { name: 'Zloty', tag: 'PLN', rate: 4.202, symbol: 'zł' },
    'RON': { name: 'Romanian Lev', tag: 'RON', rate: 4.6337, symbol: 'lei' },
    'RUB': { name: 'Russian Ruble', tag: 'RUB', rate: 69.548, symbol: '₽' },
    'SEK': { name: 'Swedish Krona', tag: 'SEK', rate: 9.968, symbol: 'kr' },
    'SGD': { name: 'Singapore Dollar', tag: 'SGD', rate: 1.5953, symbol: '$' },
    'THB': { name: 'Thai Baht', tag: 'THB', rate: 38.626, symbol: '฿' },
    'TRY': { name: 'Turkish lira', tag: 'TRY', rate: 4.5823, symbol: '₺' },
    'USD': { name: 'US Dollar', tag: 'USD', rate: 1.1847, symbol: '$' },
    'ZAR': { name: 'South African Rand', tag: 'ZAR', rate: 16.008, symbol: 'R' }
};

export const _categories: Array<string> = new Array('Entertainment', 'Food & Drinks', 'Home', 'Life', 'Transport', 'Other');